[package]
name = "Web3War"
version = "1.0.0"
authors = ["Web3War Team"]

[addresses]
web3war = "0x5b6ef2a1e31fe53dc530d8265c390cc11c105f3b33c9ed995be610401110464d"
std = "0x1"
supra_framework = "0x1"
aptos_framework = "0x1"

[dependencies]
SupraFramework = { git = "https://github.com/Entropy-Foundation/aptos-core.git", subdir = "aptos-move/framework/supra-framework", rev = "dev" }
